---
- name: Upgrade packages 
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Install core dependencies, clean
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - cloud-init
      - curl
      - gnupg-agent
      - htop
      - linux-headers-amd64
      - linux-image-amd64
      - ncdu
      - sudo
      - software-properties-common
      - tmux
      - unattended-upgrades
      - wget
      - vim
    state: present
    install_recommends: true
    autoremove: true
    autoclean: true
